import bcrypt
import threading
import time
import random
from datetime import datetime, timedelta

from flask import Blueprint, current_app, jsonify, request
from flask_jwt_extended import create_access_token, get_jwt_identity, jwt_required
from sqlalchemy import text
from sqlalchemy.exc import OperationalError, SQLAlchemyError
from werkzeug.security import check_password_hash

from activity_service import update_user_streak
from badge_service import assign_eligible_badges
from database import db
from email_service import send_email
from models import User


auth_bp = Blueprint("auth", __name__, url_prefix="/api")


LOGIN_WINDOW_SECONDS = 60
LOGIN_MAX_ATTEMPTS = 8
_login_attempts_lock = threading.Lock()
_failed_login_attempts = {}
OTP_EXPIRY_MINUTES = 5
OTP_RESEND_WINDOW_SECONDS = 600
OTP_RESEND_MAX_ATTEMPTS = 3
OTP_RESEND_COOLDOWN_SECONDS = 45
OTP_EMAIL_SUBJECT = "Your OTP Code - Gamified Learning"
PASSWORD_RESET_EXPIRY_MINUTES = 15
_otp_resend_lock = threading.Lock()
_otp_resend_attempts = {}


def _normalize_signup_role(raw_role: str | None) -> str:
    role = (raw_role or "").strip().lower()
    # Keep role compatibility with existing authorization checks.
    if role == "teacher":
        return "teacher"
    return "student"


def _generate_otp() -> str:
    return f"{random.randint(0, 999999):06d}"


def _otp_preview_enabled() -> bool:
    """Enable OTP preview only for localhost requests."""
    host = (request.host or "").split(":")[0].lower()
    return host in {"localhost", "127.0.0.1"}


def _log_local_otp(email: str, otp_code: str, context: str) -> None:
    """Log OTP generation for troubleshooting."""
    log_line = f"OTP for {email}: {otp_code} ({context})"
    current_app.logger.info(log_line)
    # Explicit print requested for quick terminal debugging.
    print(log_line)


def _build_otp_email_content(otp_code: str) -> tuple[str, str]:
    text_body = (
        "Gamified Learning\n\n"
        f"Your one-time OTP code is: {otp_code}\n"
        f"This code expires in {OTP_EXPIRY_MINUTES} minutes.\n\n"
        "If you did not request this code, you can ignore this email.\n"
        "Support: support@gamifiedlearning.quest"
    )

    html_body = (
        "<div style=\"font-family:Arial,Helvetica,sans-serif;color:#111827;line-height:1.5;\">"
        "<h2 style=\"margin:0 0 8px;\">Gamified Learning</h2>"
        "<p style=\"margin:0 0 12px;\">Verify your email with this OTP code:</p>"
        f"<div style=\"font-size:38px;font-weight:700;letter-spacing:6px;margin:8px 0 12px;\">{otp_code}</div>"
        f"<p style=\"margin:0 0 10px;\">This code expires in {OTP_EXPIRY_MINUTES} minutes.</p>"
        "<p style=\"margin:0 0 10px;\">If this wasn't you, you can ignore this message.</p>"
        "<p style=\"margin:0;color:#4b5563;\">Need help? Contact support@gamifiedlearning.quest</p>"
        "</div>"
    )

    return text_body, html_body


def _send_otp_email(email: str, text_body: str, html_body: str) -> bool:
    provider = (current_app.config.get("OTP_EMAIL_PROVIDER") or "resend").strip().lower()
    if provider not in {"resend", ""}:
        current_app.logger.warning(
            "Unsupported OTP_EMAIL_PROVIDER=%s configured; falling back to resend.",
            provider,
        )

    return send_email(
        current_app.config,
        to_email=email,
        subject=OTP_EMAIL_SUBJECT,
        text_body=text_body,
        html_body=html_body,
    )


def _get_google_client_id() -> str:
    return (current_app.config.get("GOOGLE_CLIENT_ID") or "").strip()


def _verify_google_id_token(credential: str):
    try:
        from google.auth.transport import requests as google_requests
        from google.oauth2 import id_token as google_id_token
    except Exception:
        return None, "Google auth dependency is missing on server."

    client_id = _get_google_client_id()
    if not client_id:
        return None, "Google login is not configured on server."

    try:
        token_info = google_id_token.verify_oauth2_token(
            credential,
            google_requests.Request(),
            client_id,
        )
    except Exception:
        return None, "Invalid Google token."

    if token_info.get("iss") not in ("accounts.google.com", "https://accounts.google.com"):
        return None, "Invalid Google issuer."

    if not token_info.get("email"):
        return None, "Google account email is missing."

    if not token_info.get("email_verified", False):
        return None, "Google account email is not verified."

    return token_info, None


def _ensure_pending_registration_table() -> None:
    db.session.execute(
        text(
            """
            CREATE TABLE IF NOT EXISTS pending_registrations (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(120) NOT NULL,
                email VARCHAR(255) NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                role VARCHAR(20) NOT NULL DEFAULT 'student',
                otp_hash VARCHAR(255) NOT NULL,
                otp_expiry TIMESTAMP NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_pending_registrations_email UNIQUE (email)
            );
            """
        )
    )

    db.session.execute(
        text(
            """
            CREATE INDEX IF NOT EXISTS idx_pending_registrations_expiry
            ON pending_registrations (otp_expiry)
            """
        )
    )

    role_column_exists = db.session.execute(
        text(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'pending_registrations'
              AND column_name = 'role'
            LIMIT 1
            """
        )
    ).first()

    if not role_column_exists:
        db.session.execute(
            text(
                """
                ALTER TABLE pending_registrations
                ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'student'
                """
            )
        )


def _ensure_password_reset_table() -> None:
    db.session.execute(
        text(
            """
            CREATE TABLE IF NOT EXISTS password_resets (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email VARCHAR(255) NOT NULL,
                token_hash VARCHAR(255) NOT NULL,
                token_expiry TIMESTAMP NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_password_resets_email UNIQUE (email)
            );
            """
        )
    )

    db.session.execute(
        text(
            """
            CREATE INDEX IF NOT EXISTS idx_password_resets_expiry
            ON password_resets (token_expiry)
            """
        )
    )


def _store_password_reset_token(email: str, token: str) -> None:
    token_hash = _hash_password(token)
    token_expiry = datetime.utcnow() + timedelta(minutes=PASSWORD_RESET_EXPIRY_MINUTES)
    db.session.execute(
        text(
            """
            INSERT INTO password_resets (email, token_hash, token_expiry)
            VALUES (:email, :token_hash, :token_expiry)
            ON DUPLICATE KEY UPDATE
                token_hash = VALUES(token_hash),
                token_expiry = VALUES(token_expiry)
            """
        ),
        {
            "email": email,
            "token_hash": token_hash,
            "token_expiry": token_expiry,
        },
    )


def _fetch_password_reset(email: str):
    return db.session.execute(
        text(
            """
            SELECT id, email, token_hash, token_expiry
            FROM password_resets
            WHERE email = :email
            LIMIT 1
            """
        ),
        {"email": email},
    ).mappings().first()


def _delete_password_reset(email: str) -> None:
    db.session.execute(
        text("DELETE FROM password_resets WHERE email = :email"),
        {"email": email},
    )


def _password_reset_expired(reset_row) -> bool:
    token_expiry = reset_row.get("token_expiry") if reset_row else None
    return not token_expiry or token_expiry < datetime.utcnow()


def _build_password_reset_email_content(token: str) -> tuple[str, str]:
    text_body = (
        "Gamified Learning\n\n"
        "We received a password reset request for your account.\n"
        f"Your reset code is: {token}\n"
        f"This code expires in {PASSWORD_RESET_EXPIRY_MINUTES} minutes.\n\n"
        "If you did not request this, you can ignore this email.\n"
        "Support: support@gamifiedlearning.quest"
    )

    html_body = (
        "<div style=\"font-family:Arial,Helvetica,sans-serif;color:#111827;line-height:1.5;\">"
        "<h2 style=\"margin:0 0 8px;\">Gamified Learning</h2>"
        "<p style=\"margin:0 0 12px;\">Use this code to reset your password:</p>"
        f"<div style=\"font-size:38px;font-weight:700;letter-spacing:6px;margin:8px 0 12px;\">{token}</div>"
        f"<p style=\"margin:0 0 10px;\">This code expires in {PASSWORD_RESET_EXPIRY_MINUTES} minutes.</p>"
        "<p style=\"margin:0 0 10px;\">If this wasn't you, no action is needed.</p>"
        "<p style=\"margin:0;color:#4b5563;\">Need help? Contact support@gamifiedlearning.quest</p>"
        "</div>"
    )

    return text_body, html_body


def _store_pending_registration(name: str, email: str, password_hash: str, otp_code: str, role: str) -> None:
    otp_hash = _hash_password(otp_code)
    otp_expiry = datetime.utcnow() + timedelta(minutes=OTP_EXPIRY_MINUTES)
    db.session.execute(
        text(
            """
            INSERT INTO pending_registrations (name, email, password_hash, role, otp_hash, otp_expiry)
            VALUES (:name, :email, :password_hash, :role, :otp_hash, :otp_expiry)
            ON DUPLICATE KEY UPDATE
                name = VALUES(name),
                password_hash = VALUES(password_hash),
                role = VALUES(role),
                otp_hash = VALUES(otp_hash),
                otp_expiry = VALUES(otp_expiry)
            """
        ),
        {
            "name": name,
            "email": email,
            "password_hash": password_hash,
            "role": role,
            "otp_hash": otp_hash,
            "otp_expiry": otp_expiry,
        },
    )


def _fetch_pending_registration(email: str):
    return db.session.execute(
        text(
            """
            SELECT id, name, email, password_hash, role, otp_hash, otp_expiry
            FROM pending_registrations
            WHERE email = :email
            LIMIT 1
            """
        ),
        {"email": email},
    ).mappings().first()


def _pending_otp_expired(pending_row) -> bool:
    otp_expiry = pending_row.get("otp_expiry") if pending_row else None
    return not otp_expiry or otp_expiry < datetime.utcnow()


def _update_pending_registration_otp(email: str, otp_code: str) -> None:
    otp_hash = _hash_password(otp_code)
    otp_expiry = datetime.utcnow() + timedelta(minutes=OTP_EXPIRY_MINUTES)
    db.session.execute(
        text(
            """
            UPDATE pending_registrations
            SET otp_hash = :otp_hash,
                otp_expiry = :otp_expiry
            WHERE email = :email
            """
        ),
        {
            "email": email,
            "otp_hash": otp_hash,
            "otp_expiry": otp_expiry,
        },
    )


def _otp_resend_allowed(email: str) -> tuple[bool, int]:
    now = time.time()
    with _otp_resend_lock:
        attempts = [
            ts
            for ts in _otp_resend_attempts.get(email, [])
            if ts >= now - OTP_RESEND_WINDOW_SECONDS
        ]

        # Enforce a short cooldown to prevent rapid-fire resend bursts.
        if attempts:
            elapsed = now - attempts[-1]
            if elapsed < OTP_RESEND_COOLDOWN_SECONDS:
                retry_after = int(max(1, OTP_RESEND_COOLDOWN_SECONDS - elapsed))
                _otp_resend_attempts[email] = attempts
                return False, retry_after

        _otp_resend_attempts[email] = attempts
        if len(attempts) >= OTP_RESEND_MAX_ATTEMPTS:
            retry_after = int(max(1, OTP_RESEND_WINDOW_SECONDS - (now - attempts[0])))
            return False, retry_after
        attempts.append(now)
        _otp_resend_attempts[email] = attempts
        return True, 0


def _client_ip() -> str:
    forwarded = request.headers.get("X-Forwarded-For", "")
    if forwarded:
        return forwarded.split(",")[0].strip()
    return (request.remote_addr or "unknown").strip()


def _prune_attempts(now: float) -> None:
    cutoff = now - LOGIN_WINDOW_SECONDS
    stale_ips = []
    for ip, timestamps in _failed_login_attempts.items():
        kept = [ts for ts in timestamps if ts >= cutoff]
        if kept:
            _failed_login_attempts[ip] = kept
        else:
            stale_ips.append(ip)

    for ip in stale_ips:
        _failed_login_attempts.pop(ip, None)


def _rate_limit_status(ip: str) -> tuple[bool, int]:
    now = time.time()
    with _login_attempts_lock:
        _prune_attempts(now)
        timestamps = _failed_login_attempts.get(ip, [])
        if len(timestamps) < LOGIN_MAX_ATTEMPTS:
            return False, 0

        retry_after = int(max(1, LOGIN_WINDOW_SECONDS - (now - timestamps[0])))
        return True, retry_after


def _record_failed_attempt(ip: str) -> None:
    now = time.time()
    with _login_attempts_lock:
        _prune_attempts(now)
        _failed_login_attempts.setdefault(ip, []).append(now)


def _clear_failed_attempts(ip: str) -> None:
    with _login_attempts_lock:
        _failed_login_attempts.pop(ip, None)


def _missing_fields(payload, required_fields):
    return [field for field in required_fields if not payload.get(field)]


def _hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def _check_password(password: str, hashed_password: str) -> tuple[bool, bool]:
    if not hashed_password:
        return False, False

    # Preferred path for new accounts.
    try:
        return bcrypt.checkpw(password.encode("utf-8"), hashed_password.encode("utf-8")), False
    except ValueError:
        pass

    # Backward compatibility for legacy Werkzeug hashes (e.g. scrypt/pbkdf2).
    try:
        if check_password_hash(hashed_password, password):
            return True, True
    except ValueError:
        pass

    return False, False


def _build_profile_stats(user):
    from models import Course, Enrollment, LessonProgress, Note, Problem, ProblemProgress, Progress, UserBadge

    if user.role == "teacher":
        try:
            courses_created = db.session.query(Course).filter_by(teacher_id=user.id).count()
            problems_created = db.session.query(Problem).filter_by(created_by=user.id).count()
            notes_uploaded = db.session.query(Note).filter_by(uploaded_by=user.id).count()
            students_enrolled = (
                db.session.query(Enrollment.student_id)
                .join(Course, Course.id == Enrollment.course_id)
                .filter(Course.teacher_id == user.id)
                .distinct()
                .count()
            )
            return {
                "courses_created": courses_created,
                "problems_created": problems_created,
                "students_enrolled": students_enrolled,
                "notes_uploaded": notes_uploaded,
            }
        except Exception:
            return {
                "courses_created": 0,
                "problems_created": 0,
                "students_enrolled": 0,
                "notes_uploaded": 0,
            }

    if user.role == "admin":
        try:
            total_users = db.session.query(User).count()
            total_courses = db.session.query(Course).count()
            total_problems = db.session.query(Problem).count()
            total_enrollments = db.session.query(Enrollment).count()
            return {
                "total_users": total_users,
                "total_courses": total_courses,
                "total_problems": total_problems,
                "total_enrollments": total_enrollments,
            }
        except Exception:
            return {
                "total_users": 0,
                "total_courses": 0,
                "total_problems": 0,
                "total_enrollments": 0,
            }

    try:
        courses_enrolled = db.session.query(Enrollment).filter_by(student_id=user.id).count()
        quizzes_completed = db.session.query(Progress).filter_by(user_id=user.id).count()
        problems_solved = db.session.query(ProblemProgress).filter_by(user_id=user.id, solved=True).count()
        badges_earned = db.session.query(UserBadge).filter_by(user_id=user.id).count()
        lessons_completed = db.session.query(LessonProgress).filter_by(user_id=user.id, completed=True).count()
        return {
            "courses_enrolled": courses_enrolled,
            "quizzes_completed": quizzes_completed,
            "problems_solved": problems_solved,
            "badges_earned": badges_earned,
            "lessons_completed": lessons_completed,
        }
    except Exception:
        return {
            "courses_enrolled": 0,
            "quizzes_completed": 0,
            "problems_solved": 0,
            "badges_earned": 0,
            "lessons_completed": 0,
        }


def _serialize_profile(user):
    return {
        "id": user.id,
        "name": user.name,
        "email": user.email,
        "role": user.role,
        "is_verified": user.is_verified,
        "is_approved": user.is_approved,
        "level": user.level,
        "xp_points": user.xp_points,
        "coins": user.coins,
        "streak_count": user.streak_count,
        "longest_streak": user.longest_streak,
        "last_active_date": user.last_active_date.isoformat() if user.last_active_date else None,
        "daily_streak": user.daily_streak,
        "created_at": user.created_at.isoformat(),
        "stats": _build_profile_stats(user),
    }


@auth_bp.post("/register")
@auth_bp.post("/auth/register")
def register():
    try:
        _ensure_pending_registration_table()
        data = request.get_json(silent=True) or {}
        missing = _missing_fields(data, ["name", "email", "password"])
        if missing:
            return jsonify({"success": False, "error": "Missing fields", "fields": missing}), 400

        name = data["name"].strip()
        email = data["email"].strip().lower()
        password = data["password"]
        role = _normalize_signup_role(data.get("role"))

        if not name or not email or not password:
            return jsonify({"success": False, "error": "Invalid input"}), 400

        existing_user = User.query.filter_by(email=email).first()
        if existing_user and existing_user.is_verified:
            return jsonify({"success": False, "error": "Email already registered"}), 409

        # Safety cleanup for legacy unverified rows from previous flow.
        if existing_user and not existing_user.is_verified:
            db.session.delete(existing_user)
            db.session.flush()

        password_hash = _hash_password(password)
        otp_code = _generate_otp()
        _store_pending_registration(
            name=name,
            email=email,
            password_hash=password_hash,
            otp_code=otp_code,
            role=role,
        )
        _log_local_otp(email, otp_code, "register")
        otp_text_body, otp_html_body = _build_otp_email_content(otp_code)

        db.session.commit()

        # Send OTP email and fail fast if delivery request cannot be queued.
        email_sent = _send_otp_email(
            email=email,
            text_body=otp_text_body,
            html_body=otp_html_body,
        )
        if not email_sent:
            return jsonify(
                {
                    "success": False,
                    "error": "OTP email delivery failed",
                    "message": "Unable to send OTP email right now. Please try again.",
                }
            ), 502
    except OperationalError as exc:
        db.session.rollback()
        current_app.logger.exception("Database unavailable during register: %s", exc)
        return jsonify({"success": False, "error": "Database unavailable", "message": "Please try again shortly."}), 503
    except SQLAlchemyError as exc:
        db.session.rollback()
        current_app.logger.exception("Database error during register: %s", exc)
        return jsonify({"success": False, "error": "Database error", "message": "Registration failed."}), 500

    response_payload = {
        "success": True,
        "message": "OTP sent to your email. Check spam/promotions if not found.",
        "requires_otp": True,
        "email": email,
        "sent_at": datetime.utcnow().isoformat() + "Z",
        "resend_cooldown_seconds": OTP_RESEND_COOLDOWN_SECONDS,
    }
    if _otp_preview_enabled():
        response_payload["otp_preview"] = otp_code

    return jsonify(response_payload), 202


@auth_bp.post("/verify-otp")
@auth_bp.post("/auth/verify-otp")
@auth_bp.post("/verify-registration-otp")
def verify_otp():
    try:
        _ensure_pending_registration_table()
        data = request.get_json(silent=True) or {}
        missing = _missing_fields(data, ["email", "otp"])
        if missing:
            return jsonify({"success": False, "error": "Missing fields", "fields": missing}), 400

        email = data["email"].strip().lower()
        otp = str(data["otp"]).strip()
        if len(otp) != 6 or not otp.isdigit():
            return jsonify({"success": False, "error": "Invalid OTP format"}), 400

        existing_user = User.query.filter_by(email=email).first()
        if existing_user and existing_user.is_verified:
            return jsonify({"success": True, "message": "Email already verified."}), 200

        pending_row = _fetch_pending_registration(email)
        if not pending_row:
            return jsonify({"success": False, "error": "No pending registration found."}), 404
        if _pending_otp_expired(pending_row):
            return jsonify({"success": False, "error": "OTP expired. Please request a new OTP."}), 400

        otp_ok, _ = _check_password(otp, pending_row["otp_hash"])
        if not otp_ok:
            return jsonify({"success": False, "error": "Invalid OTP"}), 400

        if existing_user and not existing_user.is_verified:
            user = existing_user
            user.name = pending_row["name"]
            user.password_hash = pending_row["password_hash"]
            user.role = _normalize_signup_role(pending_row.get("role"))
            user.is_verified = True
            user.otp_code = None
            user.otp_expiry = None
            user.is_approved = True
        else:
            user = User(
                name=pending_row["name"],
                email=pending_row["email"],
                password_hash=pending_row["password_hash"],
                role=_normalize_signup_role(pending_row.get("role")),
                is_approved=True,
                is_verified=True,
                otp_code=None,
                otp_expiry=None,
            )
            db.session.add(user)

        db.session.execute(
            text("DELETE FROM pending_registrations WHERE id = :id"),
            {"id": pending_row["id"]},
        )
        db.session.commit()

        send_email(
            current_app.config,
            to_email=user.email,
            subject="Welcome to Gamified Learning",
            text_body=(
                f"Hi {user.name},\n\n"
                "Your registration is verified and account is active.\n\n"
                "Regards,\n"
                "Gamified Learning Team"
            ),
            html_body=(
                f"<p>Hi {user.name},</p>"
                "<p>Your registration is verified and account is active.</p>"
                "<p>Regards,<br/>Gamified Learning Team</p>"
            ),
        )
        return jsonify({"success": True, "message": "Email verified successfully."}), 200
    except OperationalError as exc:
        db.session.rollback()
        current_app.logger.exception("Database unavailable during OTP verification: %s", exc)
        return jsonify({"success": False, "error": "Database unavailable", "message": "Please try again shortly."}), 503
    except SQLAlchemyError as exc:
        db.session.rollback()
        current_app.logger.exception("Database error during OTP verification: %s", exc)
        return jsonify({"success": False, "error": "Database error", "message": "OTP verification failed."}), 500


@auth_bp.post("/resend-otp")
@auth_bp.post("/auth/resend-otp")
def resend_otp():
    try:
        _ensure_pending_registration_table()
        data = request.get_json(silent=True) or {}
        missing = _missing_fields(data, ["email"])
        if missing:
            return jsonify({"success": False, "error": "Missing fields", "fields": missing}), 400

        email = data["email"].strip().lower()
        existing_user = User.query.filter_by(email=email).first()
        if existing_user and existing_user.is_verified:
            return jsonify({"success": False, "error": "Email already verified"}), 400

        pending_row = _fetch_pending_registration(email)
        if not pending_row:
            return jsonify({"success": False, "error": "No pending registration found."}), 404

        allowed, retry_after = _otp_resend_allowed(email)
        if not allowed:
            return jsonify(
                {
                    "success": False,
                    "error": "Too many resend requests",
                    "retry_after_seconds": retry_after,
                    "message": "Please wait before requesting another OTP.",
                }
            ), 429

        otp_code = _generate_otp()
        _update_pending_registration_otp(email, otp_code)
        _log_local_otp(email, otp_code, "resend")
        otp_text_body, otp_html_body = _build_otp_email_content(otp_code)
        db.session.commit()

        email_sent = _send_otp_email(
            email=email,
            text_body=otp_text_body,
            html_body=otp_html_body,
        )
        if not email_sent:
            return jsonify(
                {
                    "success": False,
                    "error": "OTP email delivery failed",
                    "message": "Unable to resend OTP right now. Please try again.",
                }
            ), 502

        response_payload = {
            "success": True,
            "message": "OTP sent to your email. Check spam/promotions if not found.",
            "sent_at": datetime.utcnow().isoformat() + "Z",
            "resend_cooldown_seconds": OTP_RESEND_COOLDOWN_SECONDS,
        }
        if _otp_preview_enabled():
            response_payload["otp_preview"] = otp_code

        return jsonify(response_payload), 200
    except OperationalError as exc:
        db.session.rollback()
        current_app.logger.exception("Database unavailable during OTP resend: %s", exc)
        return jsonify({"success": False, "error": "Database unavailable", "message": "Please try again shortly."}), 503
    except SQLAlchemyError as exc:
        db.session.rollback()
        current_app.logger.exception("Database error during OTP resend: %s", exc)
        return jsonify({"success": False, "error": "Database error", "message": "Failed to resend OTP."}), 500


@auth_bp.post("/forgot-password")
@auth_bp.post("/auth/forgot-password")
def forgot_password():
    try:
        _ensure_password_reset_table()
        data = request.get_json(silent=True) or {}
        missing = _missing_fields(data, ["email"])
        if missing:
            return jsonify({"success": False, "error": "Missing fields", "fields": missing}), 400

        email = data["email"].strip().lower()
        if not email:
            return jsonify({"success": False, "error": "Invalid input"}), 400

        user = User.query.filter_by(email=email).first()
        if user and user.is_verified:
            token = _generate_otp()
            _store_password_reset_token(email, token)
            _log_local_otp(email, token, "password-reset")
            reset_text_body, reset_html_body = _build_password_reset_email_content(token)
            db.session.commit()

            email_sent = send_email(
                current_app.config,
                to_email=email,
                subject="Reset your password - Gamified Learning",
                text_body=reset_text_body,
                html_body=reset_html_body,
            )
            if not email_sent:
                return jsonify(
                    {
                        "success": False,
                        "error": "Reset email delivery failed",
                        "message": "Unable to send reset code right now. Please try again.",
                    }
                ), 502
        else:
            db.session.commit()

        response_payload = {
            "success": True,
            "message": "If that email exists, a reset code has been sent.",
            "expires_in_minutes": PASSWORD_RESET_EXPIRY_MINUTES,
        }
        if user and user.is_verified and _otp_preview_enabled():
            response_payload["otp_preview"] = token

        return jsonify(response_payload), 200
    except OperationalError as exc:
        db.session.rollback()
        current_app.logger.exception("Database unavailable during forgot-password: %s", exc)
        return jsonify({"success": False, "error": "Database unavailable", "message": "Please try again shortly."}), 503
    except SQLAlchemyError as exc:
        db.session.rollback()
        current_app.logger.exception("Database error during forgot-password: %s", exc)
        return jsonify({"success": False, "error": "Database error", "message": "Failed to process request."}), 500


@auth_bp.post("/reset-password")
@auth_bp.post("/auth/reset-password")
def reset_password():
    try:
        _ensure_password_reset_table()
        data = request.get_json(silent=True) or {}
        missing = _missing_fields(data, ["email", "token", "new_password"])
        if missing:
            return jsonify({"success": False, "error": "Missing fields", "fields": missing}), 400

        email = data["email"].strip().lower()
        token = str(data["token"]).strip()
        new_password = str(data["new_password"])

        if not email or len(token) != 6 or not token.isdigit() or len(new_password) < 8:
            return jsonify({"success": False, "error": "Invalid input"}), 400

        user = User.query.filter_by(email=email).first()
        if not user:
            return jsonify({"success": False, "error": "Invalid reset request"}), 400

        reset_row = _fetch_password_reset(email)
        if not reset_row:
            return jsonify({"success": False, "error": "Reset code not found"}), 404

        if _password_reset_expired(reset_row):
            _delete_password_reset(email)
            db.session.commit()
            return jsonify({"success": False, "error": "Reset code expired"}), 400

        token_ok, _ = _check_password(token, reset_row["token_hash"])
        if not token_ok:
            return jsonify({"success": False, "error": "Invalid reset code"}), 400

        user.password_hash = _hash_password(new_password)
        _delete_password_reset(email)
        db.session.commit()

        return jsonify({"success": True, "message": "Password reset successful. Please log in."}), 200
    except OperationalError as exc:
        db.session.rollback()
        current_app.logger.exception("Database unavailable during reset-password: %s", exc)
        return jsonify({"success": False, "error": "Database unavailable", "message": "Please try again shortly."}), 503
    except SQLAlchemyError as exc:
        db.session.rollback()
        current_app.logger.exception("Database error during reset-password: %s", exc)
        return jsonify({"success": False, "error": "Database error", "message": "Failed to reset password."}), 500


@auth_bp.route("/login", methods=["POST", "OPTIONS"])
@auth_bp.route("/auth/login", methods=["POST", "OPTIONS"])
def login():
    if request.method == "OPTIONS":
        return jsonify({"success": True}), 200

    try:
        _ensure_pending_registration_table()
        client_ip = _client_ip()
        limited, retry_after = _rate_limit_status(client_ip)
        if limited:
            return jsonify(
                {
                    "success": False,
                    "error": "Too many attempts",
                    "message": "Too many login attempts. Please try again shortly.",
                    "retry_after_seconds": retry_after,
                }
            ), 429

        data = request.get_json(silent=True) or {}
        missing = _missing_fields(data, ["email", "password"])
        if missing:
            return jsonify(
                {
                    "success": False,
                    "error": "Missing fields",
                    "message": "Email and password are required.",
                    "fields": missing,
                }
            ), 400

        email = data["email"].strip().lower()
        password = data["password"]

        user = User.query.filter_by(email=email).first()
        if user and not user.is_verified:
            return jsonify(
                {
                    "success": False,
                    "error": "Verification required",
                    "message": "Please verify your email with OTP before logging in.",
                    "requires_otp": True,
                    "email": email,
                }
            ), 403

        if not user:
            pending_row = _fetch_pending_registration(email)
            if pending_row and not _pending_otp_expired(pending_row):
                return jsonify(
                    {
                        "success": False,
                        "error": "Verification required",
                        "message": "Please verify your email with OTP before logging in.",
                        "requires_otp": True,
                        "email": email,
                    }
                ), 403

        password_ok, needs_rehash = _check_password(password, user.password_hash if user else "")
        if not user or not password_ok:
            _record_failed_attempt(client_ip)
            return jsonify(
                {
                    "success": False,
                    "error": "Invalid credentials",
                    "message": "Invalid email or password",
                }
            ), 401

        _clear_failed_attempts(client_ip)

        if needs_rehash:
            user.password_hash = _hash_password(password)

        client_timezone = request.headers.get("X-User-Timezone")
        update_user_streak(user=user, user_timezone=client_timezone)
        newly_unlocked_badges = assign_eligible_badges(user=user, trigger="login")
        db.session.commit()

        access_token = create_access_token(
            identity=str(user.id),
            additional_claims={"role": user.role},
        )

        return jsonify(
            {
                "success": True,
                "token": access_token,
                "user": {
                    "id": user.id,
                    "name": user.name,
                    "email": user.email,
                    "role": user.role,
                    "is_verified": user.is_verified,
                    "is_approved": user.is_approved,
                    "level": user.level,
                    "xp_points": user.xp_points,
                    "coins": user.coins,
                    "streak_count": user.streak_count,
                    "longest_streak": user.longest_streak,
                    "last_active_date": user.last_active_date.isoformat() if user.last_active_date else None,
                    "daily_streak": user.daily_streak,
                },
                "unlocked_badges": newly_unlocked_badges,
            }
        )
    except OperationalError as exc:
        current_app.logger.exception("Database unavailable during login: %s", exc)
        return jsonify(
            {
                "success": False,
                "error": "Database unavailable",
                "message": "Please try again shortly.",
            }
        ), 503
    except SQLAlchemyError as exc:
        current_app.logger.exception("Database error during login: %s", exc)
        return jsonify(
            {
                "success": False,
                "error": "Database error",
                "message": "Login failed. Please retry.",
            }
        ), 500


@auth_bp.post("/auth/google-login")
def google_login():
    try:
        payload = request.get_json(silent=True) or {}
        credential = str(payload.get("credential", "")).strip()
        if not credential:
            return jsonify({"success": False, "error": "Missing Google credential."}), 400

        token_info, token_error = _verify_google_id_token(credential)
        if token_error:
            return jsonify({"success": False, "error": token_error}), 401

        email = token_info["email"].strip().lower()
        name = (token_info.get("name") or email.split("@")[0]).strip()[:120]

        user = User.query.filter_by(email=email).first()
        if user and user.role == "teacher" and user.is_approved is False:
            return jsonify(
                {
                    "success": False,
                    "error": "Teacher approval pending.",
                }
            ), 403

        if not user:
            # password_hash is required by schema; random hash prevents password auth with empty values.
            user = User(
                name=name,
                email=email,
                password_hash=_hash_password(str(random.randint(100000, 999999))),
                role="student",
                is_approved=True,
                is_verified=True,
                otp_code=None,
                otp_expiry=None,
            )
            db.session.add(user)
            db.session.flush()
        else:
            user.name = user.name or name
            user.is_verified = True

        client_timezone = request.headers.get("X-User-Timezone")
        update_user_streak(user=user, user_timezone=client_timezone)
        newly_unlocked_badges = assign_eligible_badges(user=user, trigger="login")
        db.session.commit()

        access_token = create_access_token(
            identity=str(user.id),
            additional_claims={"role": user.role},
        )

        return jsonify(
            {
                "success": True,
                "token": access_token,
                "user": {
                    "id": user.id,
                    "name": user.name,
                    "email": user.email,
                    "role": user.role,
                    "is_verified": user.is_verified,
                    "is_approved": user.is_approved,
                    "level": user.level,
                    "xp_points": user.xp_points,
                    "coins": user.coins,
                    "streak_count": user.streak_count,
                    "longest_streak": user.longest_streak,
                    "last_active_date": user.last_active_date.isoformat() if user.last_active_date else None,
                    "daily_streak": user.daily_streak,
                },
                "unlocked_badges": newly_unlocked_badges,
            }
        )
    except OperationalError as exc:
        db.session.rollback()
        current_app.logger.exception("Database unavailable during Google login: %s", exc)
        return jsonify({"success": False, "error": "Database unavailable"}), 503
    except SQLAlchemyError as exc:
        db.session.rollback()
        current_app.logger.exception("Database error during Google login: %s", exc)
        return jsonify({"success": False, "error": "Database error"}), 500


@auth_bp.get("/profile")
@jwt_required()
def profile():
    user_id = get_jwt_identity()
    user = User.query.get(int(user_id))
    if not user:
        return jsonify({"error": "User not found"}), 404

    return jsonify(_serialize_profile(user))


@auth_bp.patch("/profile")
@auth_bp.patch("/auth/profile")
@auth_bp.put("/profile")
@auth_bp.put("/auth/profile")
@jwt_required()
def update_profile():
    user_id = get_jwt_identity()
    user = User.query.get(int(user_id))
    if not user:
        return jsonify({"error": "User not found"}), 404

    data = request.get_json(silent=True) or {}
    name = data.get("name")
    email = data.get("email")

    if name is None and email is None:
        return jsonify({"error": "No fields to update"}), 400

    if name is not None:
        name = name.strip()
        if not name:
            return jsonify({"error": "Name cannot be empty"}), 400
        user.name = name

    if email is not None:
        email = email.strip().lower()
        if not email:
            return jsonify({"error": "Email cannot be empty"}), 400
        existing_user = User.query.filter(User.email == email, User.id != user.id).first()
        if existing_user:
            return jsonify({"error": "Email already registered"}), 409
        user.email = email

    db.session.commit()
    return jsonify(_serialize_profile(user))


@auth_bp.post("/auth/logout")
@jwt_required()
def logout():
    return jsonify({"success": True, "message": "Logged out"})


@auth_bp.post("/auth/change-password")
@jwt_required()
def change_password():
    user_id = get_jwt_identity()
    user = User.query.get(int(user_id))
    if not user:
        return jsonify({"success": False, "message": "User not found"}), 404

    payload = request.get_json(silent=True) or {}
    current_password = payload.get("current_password")
    new_password = payload.get("new_password")
    confirm_password = payload.get("confirm_password")

    if not current_password or not new_password or not confirm_password:
        return (
            jsonify(
                {
                    "success": False,
                    "message": "current_password, new_password and confirm_password are required.",
                }
            ),
            400,
        )

    if new_password != confirm_password:
        return jsonify({"success": False, "message": "New passwords do not match."}), 400

    if len(new_password) < 8:
        return jsonify({"success": False, "message": "New password must be at least 8 characters."}), 400

    current_ok, _ = _check_password(current_password, user.password_hash)
    if not current_ok:
        return jsonify({"success": False, "message": "Current password is incorrect."}), 400

    user.password_hash = _hash_password(new_password)
    db.session.commit()

    return jsonify({"success": True, "message": "Password updated successfully."}), 200
